services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
    ports:
      - 13306:3306
