# Generated by Django 5.1.1 on 2024-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0009_remove_results_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=models.Index(fields=["status"], name="django_task_status_9e2de0_idx"),
        ),
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=models.Index(
                fields=["queue_name"], name="django_task_queue_n_99c321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=models.Index(
                models.OrderBy(models.F("priority"), descending=True),
                models.OrderBy(models.F("run_after"), descending=True, nulls_last=True),
                name="idx_task_ordering",
            ),
        ),
    ]
