# Generated by Django 5.1.6 on 2025-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0014_remove_dbtaskresult_exception_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtaskresult",
            name="timeout",
            field=models.PositiveBigIntegerField(default=600, verbose_name="timeout"),
        ),
    ]
