# Generated by Django 5.1.6 on 2025-02-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0014_remove_dbtaskresult_exception_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtaskresult",
            name="worker_id",
            field=models.CharField(default="", max_length=64, verbose_name="worker id"),
        ),
    ]
