# Generated by Django 5.1.5 on 2025-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0014_remove_dbtaskresult_exception_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtaskresult",
            name="worker_id",
            field=models.UUIDField(null=True, verbose_name="worker id"),
        ),
    ]
