# Generated by Django 5.1.5 on 2025-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0014_remove_dbtaskresult_exception_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBWorkerPing",
            fields=[
                (
                    "worker_id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("last_ping", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="dbtaskresult",
            name="worker_id",
            field=models.CharField(default="", max_length=64, verbose_name="worker id"),
        ),
    ]
