# Generated by Django 5.1.5 on 2025-02-01 13:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0015_dbtaskresult_worker_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBWorkerPing",
            fields=[
                (
                    "worker_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_ping", models.DateTimeField()),
            ],
        ),
    ]
