# Generated by Django 5.1.4 on 2025-05-07 19:10

from django.db import migrations

import django_tasks.backends.database.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0016_alter_dbtaskresult_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbtaskresult",
            name="run_after",
            field=django_tasks.backends.database.models.NullIsMaxDateTimeField(
                verbose_name="run after"
            ),
        ),
    ]
