# Generated by Django 4.2 on 2025-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0018_dbtaskresult_worker_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtaskresult",
            name="worker_id",
        ),
        migrations.AddField(
            model_name="dbtaskresult",
            name="worker_ids",
            field=models.JSONField(default=list, verbose_name="worker id"),
        ),
    ]
